---
language: generic

sudo: required
dist: trusty

services:
- docker

install:
- docker run --rm -v $(pwd):/usr/src/app tomasbasham/protoc:3.6.1-go -I ./proto --go_out=plugins=grpc:. comment.proto
- docker build -t comment --target builder .

script:
- docker run --rm comment golint -set_exit_status ./...
- docker run --rm comment go vet ./...
- docker run --rm comment go test ./...

notifications:
  email: false
